### ISSUE TITLE
Floppy saving and replacing battery

### ISSUE THREAD

**Issue by RaymiiOrg** [tomverbeure/tek420a#2]
Do you know if you can use the floppy method to save the nvram, then replace the 2 batteries and restore the data, to keep calibration?

I dont have a GBIP module, maybe you can confirm if this is a workable solution. 

Im not sure about the data on the nvram, but some say it's calibration and without it the scope is useless...

**Comment by tomverbeure** [comment]
I've heard that the NVRAM data contains important calibration info, but I don't know if the scope will still work if the data has been erased. I'm also not aware of a way to back up this data with a floppy.

I recently sold it, so my TDS 420A chapter has come to an end.

Tom

**Comment by RaymiiOrg** [comment]
Thanks for responding anyway,, even though you sold yours!
